# Do not edit. Generated by the configure script.
export PATH:=/tmp/usr/ports/www/node/work/node-v17.0.1/out/tools/bin:$(PATH)
BUILDTYPE=Release
NODE_TARGET_TYPE=executable
PYTHON=/usr/local/bin/python3.8
PREFIX=/usr/local
